name: CONUS_carbon-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - blosc=1.21.1=h83bc5f7_3
  - boost-cpp=1.74.0=h75c5d50_8
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1013
  - cfitsio=4.1.0=hd9d235c_0
  - curl=7.83.1=h2283fc2_0
  - expat=2.4.8=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - freexl=1.0.6=h7f98852_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=12.1.0=hea43390_16
  - gdal=3.5.1=py310he53f9b6_5
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_3
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=12.1.0=h1db8e46_16
  - giflib=5.2.1=h36c2ea0_2
  - glpk=5.0=h445213a_0
  - gmp=6.2.1=h58526e2_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=12.1.0=hea43390_16
  - harfbuzz=5.1.0=hf9f4e7c_0
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.12.2=nompi_h4df4325_100
  - icu=70.1=h27087fc_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - kealib=1.4.15=ha7026e8_1
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.83.1=h2283fc2_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=12.1.0=h1ec3361_16
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.1=h84f2e82_5
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=16_linux64_openblas
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.37=h753d276_4
  - libpq=14.5=he2d8382_0
  - librttopo=1.1.0=hf730bdb_11
  - libsanitizer=12.1.0=ha89aaad_16
  - libspatialite=5.0.1=h38b5f51_18
  - libsqlite=3.39.3=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=12.1.0=h1ec3361_16
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_4
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.12=h166bdaf_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.3=hd18ef5c_1
  - ncurses=6.3=h27087fc_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.2=py310h53a5b5f_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.5=h166bdaf_2
  - pango=1.50.9=hc4f8a73_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=22.04.0=h8b295ee_2
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=ha7cec9f_0
  - proj=9.0.1=h93bde94_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.10.6=ha86cf86_0_cpython
  - python_abi=3.10=2_cp310
  - r-assertthat=0.2.1=r41hc72bb7e_2
  - r-backports=1.4.1=r41hcfec24a_0
  - r-base=4.1.3=ha8c3e7c_2
  - r-base64url=1.4=r41hcfec24a_1004
  - r-batchtools=0.9.15=r41hcfec24a_0
  - r-bit=4.0.4=r41hcfec24a_0
  - r-bit64=4.0.5=r41hcfec24a_0
  - r-brew=1.0_7=r41hc72bb7e_0
  - r-brio=1.1.3=r41hcfec24a_0
  - r-callr=3.7.2=r41hc72bb7e_0
  - r-checkmate=2.1.0=r41h06615bd_0
  - r-class=7.3_20=r41hcfec24a_0
  - r-classint=0.4_7=r41h8da6f51_0
  - r-cli=3.4.0=r41h7525677_0
  - r-clipr=0.8.0=r41hc72bb7e_0
  - r-codetools=0.2_18=r41hc72bb7e_0
  - r-colorspace=2.0_3=r41h06615bd_0
  - r-commonmark=1.8.0=r41h06615bd_0
  - r-cowplot=1.1.1=r41hc72bb7e_0
  - r-cpp11=0.4.2=r41hc72bb7e_0
  - r-crayon=1.5.1=r41hc72bb7e_0
  - r-data.table=1.14.2=r41hcfec24a_0
  - r-dbi=1.1.3=r41hc72bb7e_0
  - r-desc=1.4.2=r41hc72bb7e_0
  - r-diffobj=0.3.5=r41hcfec24a_0
  - r-digest=0.6.29=r41h03ef668_0
  - r-doparallel=1.0.17=r41hc72bb7e_0
  - r-dplyr=1.0.10=r41h7525677_0
  - r-e1071=1.7_11=r41h7525677_0
  - r-ellipsis=0.3.2=r41hcfec24a_0
  - r-evaluate=0.16=r41hc72bb7e_0
  - r-fansi=1.0.3=r41h06615bd_0
  - r-farver=2.1.1=r41h7525677_0
  - r-foreach=1.5.2=r41hc72bb7e_0
  - r-fs=1.5.2=r41h7525677_1
  - r-future=1.28.0=r41hc72bb7e_0
  - r-future.batchtools=0.10.0=r41hc72bb7e_0
  - r-ga=3.2.2=r41h03ef668_0
  - r-generics=0.1.3=r41hc72bb7e_0
  - r-ggplot2=3.3.6=r41hc72bb7e_0
  - r-globals=0.16.1=r41hc72bb7e_0
  - r-glue=1.6.2=r41h06615bd_0
  - r-gtable=0.3.1=r41hc72bb7e_0
  - r-highr=0.9=r41hc72bb7e_0
  - r-hms=1.1.2=r41hc72bb7e_0
  - r-igraph=1.3.4=r41hb34fc8a_0
  - r-isoband=0.2.5=r41h03ef668_0
  - r-iterators=1.0.14=r41hc72bb7e_0
  - r-jsonlite=1.8.0=r41h06615bd_0
  - r-kernsmooth=2.23_20=r41h742201e_0
  - r-knitr=1.40=r41hc72bb7e_0
  - r-labeling=0.4.2=r41hc72bb7e_1
  - r-lattice=0.20_45=r41hcfec24a_0
  - r-lifecycle=1.0.1=r41hc72bb7e_0
  - r-listenv=0.8.0=r41hc72bb7e_1
  - r-lubridate=1.8.0=r41h03ef668_0
  - r-magrittr=2.0.3=r41h06615bd_0
  - r-mass=7.3_58.1=r41h06615bd_0
  - r-matrix=1.4_1=r41h0154571_0
  - r-metrics=0.1.4=r41hc72bb7e_1002
  - r-mgcv=1.8_40=r41h0154571_0
  - r-munsell=0.5.0=r41hc72bb7e_1004
  - r-nlme=3.1_159=r41h8da6f51_0
  - r-parallelly=1.32.1=r41hc72bb7e_0
  - r-pillar=1.8.1=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_1
  - r-pkgload=1.3.0=r41hc72bb7e_0
  - r-plyr=1.8.7=r41h7525677_0
  - r-praise=1.0.0=r41hc72bb7e_1005
  - r-prettyunits=1.1.1=r41hc72bb7e_1
  - r-processx=3.7.0=r41h06615bd_0
  - r-progress=1.2.2=r41hc72bb7e_2
  - r-proxy=0.4_27=r41h06615bd_0
  - r-ps=1.7.1=r41h06615bd_0
  - r-purrr=0.3.4=r41hcfec24a_1
  - r-r6=2.5.1=r41hc72bb7e_0
  - r-rappdirs=0.3.3=r41hcfec24a_0
  - r-rcolorbrewer=1.1_3=r41h785f33e_0
  - r-rcpp=1.0.9=r41h7525677_1
  - r-rcpparmadillo=0.11.2.3.1=r41h9f5de39_0
  - r-readr=2.1.2=r41h03ef668_0
  - r-rematch2=2.1.2=r41hc72bb7e_1
  - r-rlang=1.0.5=r41h7525677_0
  - r-roxygen2=7.2.1=r41h7525677_0
  - r-rprojroot=2.0.3=r41hc72bb7e_0
  - r-s2=1.1.0=r41h5be344c_0
  - r-scales=1.2.1=r41hc72bb7e_0
  - r-sf=1.0_7=r41h3f368ee_3
  - r-sp=1.5_0=r41h06615bd_0
  - r-stringi=1.7.8=r41h30a9eb7_0
  - r-stringr=1.4.1=r41hc72bb7e_0
  - r-tarchetypes=0.7.1=r41hc72bb7e_0
  - r-targets=0.13.1=r41hc72bb7e_0
  - r-terra=1.5_21=r41h9b3b9be_5
  - r-testthat=3.1.4=r41h7525677_0
  - r-tibble=3.1.8=r41h06615bd_0
  - r-tidyr=1.2.1=r41h7525677_0
  - r-tidyselect=1.1.2=r41hc72bb7e_0
  - r-tzdb=0.3.0=r41h7525677_0
  - r-units=0.8_0=r41h7525677_0
  - r-utf8=1.2.2=r41hcfec24a_0
  - r-vctrs=0.4.1=r41h7525677_0
  - r-viridislite=0.4.1=r41hc72bb7e_0
  - r-vroom=1.5.7=r41h03ef668_0
  - r-waldo=0.4.0=r41hc72bb7e_0
  - r-withr=2.5.0=r41hc72bb7e_0
  - r-wk=0.6.0=r41h03ef668_0
  - r-xfun=0.32=r41h7525677_0
  - r-xml2=1.3.3=r41h7525677_1
  - r-yaml=2.3.5=r41h06615bd_0
  - readline=8.1.2=h0f457ee_0
  - sed=4.8=he412f7d_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - snappy=1.1.9=hbd366e4_1
  - sqlite=3.39.3=h4ff8645_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tiledb=2.11.1=h3f4058f_0
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - tzcode=2022c=h166bdaf_0
  - tzdata=2022c=h191b570_0
  - udunits2=2.2.28=hc3e0081_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h55805fa_5
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h6239696_4
prefix: /work/cbrinkerhoff_umass_edu/.conda/envs/CONUS_carbon-env
